yolo_model:

  config_file:
    name: yolov4-custom-dsti.cfg
  weight_file:
    name: yolov4-custom-dsti_final.weights
  threshold:
    value: 0.35
  detection_classes:
    names:
      - Tomato
      - Tomato (group)
      - Apple
      - Apple (group)
      - Banana
      - Banana (group)
      - Mango
      - Mango (group)
      - Blank
      - Tomato (bag)
      - Banana (bag)
      - Apple (bag)
      - Mango (bag)
      - Tomato (inside bag)
      - Apple (inside bag)
      - Mango (inside bag)
      - Banana (inside bag)
