yolo_model:

  config_file:
    name: yolov2-tiny-strawplant.cfg
  weight_file:
    name: yolov2-tiny.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - pottedplant
      - vase
