# k_gains:
#         - 1400.0
#         - 1400.0
#         - 1400.0
#         - 375.0
#         - 375.0
#         - 375.0
# d_gains:
#         - 30.0
#         - 30.0
#         - 30.0
#         - 3.0
#         - 3.0
#         - 3.0

k_gains:
        - 1500.0
        - 1500.0
        - 1500.0
        - 1
        - 1
        - 1
d_gains:
        - 25.0
        - 25.0
        - 25.0
        - 0.0
        - 0.0
        - 0.0

# k_gains:
#         - 1000.0
#         - 1000.0
#         - 1000.0
#         - 350.0
#         - 350.0
#         - 350.0
# d_gains:
#         - 30.0
#         - 30.0
#         - 30.0
#         - 3.0
#         - 3.0
#         - 3.0